apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260519-234654-0849xygghx73-service
spec:
  selector:
    app: enterprise-system-20260519-234654-0849xygghx73
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
